package com.vigoss.shop.sys.entity;

import java.io.Serializable;
import java.util.Date;

public class SysMacro implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_macro.id
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_macro.parent_id
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_macro.name
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_macro.value
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_macro.status
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_macro.type
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_macro.order_num
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_macro.remark
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_macro.gmt_create
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_macro.gmt_modified
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_macro.id
     *
     * @return the value of sys_macro.id
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_macro.id
     *
     * @param id the value for sys_macro.id
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_macro.parent_id
     *
     * @return the value of sys_macro.parent_id
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_macro.parent_id
     *
     * @param parentId the value for sys_macro.parent_id
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_macro.name
     *
     * @return the value of sys_macro.name
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_macro.name
     *
     * @param name the value for sys_macro.name
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_macro.value
     *
     * @return the value of sys_macro.value
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_macro.value
     *
     * @param value the value for sys_macro.value
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_macro.status
     *
     * @return the value of sys_macro.status
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_macro.status
     *
     * @param status the value for sys_macro.status
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_macro.type
     *
     * @return the value of sys_macro.type
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_macro.type
     *
     * @param type the value for sys_macro.type
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_macro.order_num
     *
     * @return the value of sys_macro.order_num
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_macro.order_num
     *
     * @param orderNum the value for sys_macro.order_num
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_macro.remark
     *
     * @return the value of sys_macro.remark
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_macro.remark
     *
     * @param remark the value for sys_macro.remark
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_macro.gmt_create
     *
     * @return the value of sys_macro.gmt_create
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_macro.gmt_create
     *
     * @param gmtCreate the value for sys_macro.gmt_create
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_macro.gmt_modified
     *
     * @return the value of sys_macro.gmt_modified
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_macro.gmt_modified
     *
     * @param gmtModified the value for sys_macro.gmt_modified
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}