package com.vigoss.shop.sys.entity;

import java.io.Serializable;

public class SysRegion implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.id
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.parent_id
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.name
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.type
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.agency_id
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    private Integer agencyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.id
     *
     * @return the value of sys_region.id
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.id
     *
     * @param id the value for sys_region.id
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.parent_id
     *
     * @return the value of sys_region.parent_id
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.parent_id
     *
     * @param parentId the value for sys_region.parent_id
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.name
     *
     * @return the value of sys_region.name
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.name
     *
     * @param name the value for sys_region.name
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.type
     *
     * @return the value of sys_region.type
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.type
     *
     * @param type the value for sys_region.type
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.agency_id
     *
     * @return the value of sys_region.agency_id
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public Integer getAgencyId() {
        return agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.agency_id
     *
     * @param agencyId the value for sys_region.agency_id
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    public void setAgencyId(Integer agencyId) {
        this.agencyId = agencyId;
    }
}