package com.vigoss.shop.sys.dao.mapper;

import com.vigoss.shop.sys.entity.SysMacro;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface SysMacroMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_macro
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_macro
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    int insert(SysMacro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_macro
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    SysMacro selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_macro
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    List<SysMacro> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_macro
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    int updateByPrimaryKey(SysMacro record);

    int deleteBatch(Long[] id);

    List<SysMacro> queryList(Map<String, Object> map);

    /**
     * 查询数据字段
     *
     * @param value
     * @return
     */
    List<SysMacro> queryMacrosByValue(@Param("value") String value);

    int queryTotal(Map<String, Object> map);
}