package com.vigoss.shop.sys.dao.mapper;

import com.vigoss.shop.sys.entity.SysRegion;
import java.util.List;
import java.util.Map;

public interface SysRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    int insert(SysRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    SysRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    List<SysRegion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated Mon May 21 20:20:06 CST 2018
     */
    int updateByPrimaryKey(SysRegion record);

    int deleteBatch(Object[] id);

    List<SysRegion> queryList(Map<String, Object> map);

    int queryTotal(Map<String, Object> map);
}